baseURL = "andbible-tutorial.netlify.app"
title = "Andbible AIGC Tutorial Hub"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["xltdoc", "docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = false

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

[languages]
[languages.en]
languageName ="English"
weight = 1
[languages.en.params]
title = "Andbible AIGC Tutorial Hub"
description = "Andbible AIGC Tutorial Hub"

#[languages.zh]
#languageName ="中文"
#weight = 2
#contentDir = "content/zh"
#[languages.zh.params]
#title = "Andbible 知识中心"
#description = "Andbible 知识中心"
#time_format_default = "2006-12-26"
#time_format_blog = "2006-12-26"

# Language configuration

disableKinds = ["taxonomy"]

# log warning if link does not exist on build (instead of default ERROR, which fails the build)
refLinksErrorLevel = "WARNING"

[frontmatter]
date = [":git", "lastmod", "date", "publishDate", ":fileModTime"]
lastmod = [":git", "lastmod", "date", "publishDate", ":fileModTime"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      codeFences = true
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = false
      style = "tango"
      tabWidth = 4



 # First one is picked as the Twitter card image if not set on page.
 #images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"
release-notes = "/release-notes/:title/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 85
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
#id = "UA-00000000-0"



# Everything below this are Site Params

[params]
copyright = "https://andbible-tutorial.netlify.app/"
privacy_policy = "https://andbible-tutorial.netlify.app/privacy.html"
doc_license = "'https://www.example.org/licenses/LICENSE-2.0'"
host = "andbible-tutorial.netlify.app"

rss_sections = ["sqlite"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
# version_menu = "Releases"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/Xceptance/xlt-documentation"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/Xceptance/XLT"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
# (if this is enabled, sidebar_search_disable needs to be true as well, Algolia does not support sidebar search)
#algolia_docsearch = true

# Enable local search
# offlineSearch = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
#yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
#no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discussion and help from your fellow users"
#[[params.links.user]]
#	name ="Twitter"
#	url = "https://example.org/twitter"
#	icon = "fab fa-twitter"
#        desc = "Follow us on Twitter to get the latest news!"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
#        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.

#[[params.links.developer]]
#	name = "GitHub"
#	url = "https://github.com/Xceptance/xlt-documentation"
#	icon = "fab fa-github"
 #       desc = "Development takes place here!"
#[[params.links.developer]]
#	name = "Twitter"
#	url = "https://twitter.com/Xceptance"
#	icon = "fab fa-twitter"
#       desc = "Follow Xceptance on Twitter for more updates"
#[[params.links.developer]]
#	name = "Blog"
#	url = "https://blog.xceptance.com/"
#	icon = "fa fa-newspaper"
#        desc = "The Xceptance Blog"





# Main menu configuration





[[menu.main]]
    identifier = "sqlite"
    name = "SQLite"
    weight = 5
    url = "/sqlite/"
[[menu.main]]
    name = "Getting Started"
    weight = 100
    url = "/sqlite/getting-started/"
    parent = "sqlite"
[[menu.main]]
    name = "Fundamentals"
    weight = 200
    url = "/sqlite/fundamentals/"
    parent = "sqlite"
[[menu.main]]
    name = "Creating and Managing databases"
    weight = 300
    url = "/sqlite/creating-and-managing-databases/"
    parent = "sqlite"
[[menu.main]]
    name = "Working with data"
    weight = 400
    url = "/sqlite/working-with-data/"
    parent = "sqlite"
[[menu.main]]
    name = "Advanced Querying"
    weight = 500
    url = "/sqlite/advanced-querying/"
    parent = "sqlite"
[[menu.main]]
    name = "Data Modification"
    weight = 600
    url = "/sqlite/data-modification/"
    parent = "sqlite"

[[menu.main]]
    name = "SQLite Functions"
    weight = 700
    url = "/sqlite/sqlite-functions/"
    parent = "sqlite"

[[menu.main]]
    name = "Data Types"
    weight = 800
    url = "/sqlite/data-types/"
    parent = "sqlite"

[[menu.main]]
    name = "Table Relations and Joins"
    weight = 900
    url = "/sqlite/400-sqlite-understanding-sql-joins-in-sqlite/"
    parent = "sqlite"

[[menu.main]]
    name = "Transaction"
    weight = 1000
    url = "/sqlite/transaction-and-integrity/"
    parent = "sqlite"

[[menu.main]]
    name = "Performace Optimization"
    weight = 1100
    url = "/sqlite/performace-optimization/"
    parent = "sqlite"

[[menu.main]]
    name = "Advanved Features"
    weight = 1200
    url = "/sqlite/advanced-features/"
    parent = "sqlite"

[[menu.main]]
    name = "Best Practices"
    weight = 1200
    url = "/sqlite/sqlite-best-pratices/"
    parent = "sqlite"

[[menu.main]]
    name = "Common Issues"
    weight = 1200
    url = "/sqlite/common-pitfalls/"
    parent = "sqlite"